[package]
name = "git-oipfs"
version = "0.1.0"
edition = "2021"

[dependencies]
gix = { version = "0.87", default-features = false, features = [
    "blob-diff",
    "revision",
    "merge",
    "max-performance-safe",
    "sha1",
    "blocking-network-client",
    "blocking-http-transport-reqwest-rust-tls",
    "worktree-mutation",
] }
serde = "1.0.229"
toml = "1.1.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
