# syntax=docker/dockerfile:1

# ---- Build stage ----
FROM docker.io/library/rust:1 AS build

WORKDIR /build

# Build the binary
COPY ./ ./
RUN cargo build --release
RUN mkdir /out
RUN ls target/release/ -la
COPY target/release/git-oipfs /out/oipfs

# ---- Runtime stage ----
FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app

COPY --from=build /out/oipfs /app/oipfs

ENTRYPOINT ["/app/oipfs"]
