services:
  ipfs:
    image: docker.io/ipfs/kubo:latest
    container_name: ipfs
    restart: unless-stopped
    volumes:
      - ipfs_data:/data/ipfs
      - ./website:/site:ro
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
  git-oipfs:
    build:
      context: ../app
    container_name: git-oipfs
    restart: unless-stopped
    environment:
      - OIPFS_REPOSITORY_PATH=/repo
    volumes:
      - ./repo:/repo:ro
volumes:
  ipfs_data:
